name: Lint

on:
  pull_request:
    paths-ignore: ["**.md"]
  push:
    branches: ["main"]
    paths-ignore: ["**.md"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
