name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types: [completed]

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14.x, 16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use node@${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run ci:test
      - name: Report code coverage
        uses: codecov/codecov-action@v2
